[addressbooks]
[[kontakty]]
path = /storage/pawelkonfig/kontakty/

[general]
debug = no
default_action = list
editor = vim
merge_editor = vimdiff

[contact table]
display = formatted_name
group_by_addressbook = no
localize_dates = yes
preferred_email_address_type = pref, work, home
preferred_phone_number_type = pref, cell, work, home
reverse = no
show_nicknames = no
show_uids = no
show_kinds = no
